### PR TITLE
fix: missing 'properties' object in query param

### LINKED ISSUE #110: Query param type error
When using the “Object/Hash” query param type, after saving and viewing the docs I get the following error on the page:

image

### PR DESCRIPTION
**Pull request by nadalfederer**
closes #110
I've added an example to response-schema.json
Here how does it looked before fixing a bug
image
Here how does it look now
image
The bug occurred because we have passed incorrect json to `react-jsonschema-form`

### CODE REVIEW

**Comment by domharrington** [comment]
I think this is a good start, but typing into the input, the object does not appear in the URL at all. Maybe we need to work on #14 as well in order to support more use cases.

**Comment by erunion** [comment]
@nadalfederer Can you update this branch?

**Comment by nadalfederer** [comment]
Sure, I'll do it soon

**Comment by nadalfederer** [comment]
Sure, I'll do it soon

**Comment by nadalfederer** [comment]
@erunion I've resolved conflicts

**Pull request closed without merging**
