### PR TITLE
feat: Adding support for multiple media types

### PR DESCRIPTION
**Pull request by erunion**
###### See https://github.com/readmeio/api-explorer/pull/231 for previous discussion.

This adds support for rendering out responses that support multiple media types and is built off of the great work done in #208.

### Mockups
63114707-8117d100-bf63-11e9-85e3-1cab0cf5899f

63114708-8117d100-bf63-11e9-9f57-a60fe622052f

### CODE REVIEW

**Comment by erunion** [comment]
@rafegoldberg This is ready for your magic. http://localhost:9966/?selected=swagger-files%2Fmultiple-media-types.json is magic link to see all these test cases with. Just need the dropdowns styled how @madisonyocum has them in the design.

**Comment by rafegoldberg** [comment]
how's this?

image

**Comment by erunion** [comment]
Brilliant

**Comment by erunion** [comment]
This is ready for review! 

Since we only have support for JSON parameters right now, not included with this feature is the ability to dynamically swap out `Content-Type` headers and different parameters with them.

**Pull request merged**
