### PR TITLE
chore(deps-dev): install RDMD as a peer

### PR DESCRIPTION
**Pull request by rafegoldberg**
## 🧰 What's being changed?

This PR is to simplify installs, reverts, and hotfixes between the Explorer, ReadMe, and their shared RDMD dependency.

- [x] Move RDMD to `peerDependencies` 
- [x] Externalize RDMD deps [in webpack](https://github.com/readmeio/api-explorer/blob/86176bde3803dfd72f453fc4c19cc21401dc408c/packages%2Fapi-explorer%2Fwebpack.config.js#L6).
  https://github.com/readmeio/api-explorer/blob/86176bde3803dfd72f453fc4c19cc21401dc408c/packages%2Fapi-explorer%2Fwebpack.config.js#L5-L6

## 🧪 Testing

This works if...
- the Explorer runs as expected in [the integration PR app](https://github.com/readmeio/readme/pull/3227)!
- we see [smaller Explorer build sizes](https://github.com/readmeio/api-explorer/pull/1052#issuecomment-730153396).

### CODE REVIEW

**Comment by rafegoldberg** [comment]
Still interested to see how it works in a ReadMe-side staging PR app, but I tested this locally (with `npm link`) and it worked as expected!

**Review by erunion — APPROVED** [review]
This all looks good to me but I'm definitely nervous about how it'll work in prod. @rafegoldberg you want me to tag an RC with this for you to test in a PR app with?

**Comment by rafegoldberg** [comment]
@erunion agreed, a bit hair raising. An RC would be amazing.

**Comment by erunion** [comment]
This is super promising.

#### Before
```
$ du -hs packages/api-explorer/dist
4.9M	packages/api-explorer/dist
```

#### After
```
$ du -hs packages/api-explorer/dist
4.1M	packages/api-explorer/dist
```

**Comment by erunion** [comment]
The merge conflict on this is a wreck so I'm moving this into https://github.com/readmeio/api-explorer/pull/1064

**Pull request closed without merging**
