### PR TITLE
add empty `properties` key to type 'object'

### LINKED ISSUE #174: Explorer doesn't render when the object reference is empty
Look at the following code: 

```
/endpoints/{deploymentName}/datavec/{transformName}/{versionName}/transformprocess:
    post:
      operationId: transformprocess_post
      summary: Sets the deployed (CSV or Image) transform process through the provided JSON string
      tags:
      - Transform
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: deploymentName
        in: path
        description: Name of the deployment group
        required: true
        type: string
      - name: versionName
        in: path
        description: Version name of the endpoint. The default value is "default"
        required: true
        default: default
        type: string
      - name: transformName
        in: path
        description: ID or name of the deployed transform
        required: true
        type: string
      - in: body
        name: TransformProcess
        description: The transform process to set
        schema:
          type: object
      responses:
        200:
          description: transform process set successfully
          schema:
            type: object
        500:
          description: internal server error
```

It gives the following output in the api-explorer:

capture

By saying: `Invalid root object field configuration:Cannot convert undefined or null to object.`

**Proposal**
Maybe a better way to deal with this case is to show nothing under the `BODY PARAMS` header.

### PR DESCRIPTION
**Pull request by nadalfederer**
closes #174

### CODE REVIEW

**Comment by nadalfederer** [comment]
@domharrington Can you check this. Is it the right approach to do this task?

**Comment by domharrington** [comment]
Hey! So it looks like there's been a fix for this in the upstream form module which defaults it to `{}` if it's not set. This would be a much simpler solution if we can just bring this in from upstream: https://github.com/mozilla-services/react-jsonschema-form/blob/f9d4c63cac24146e522528d33eb04f465464e052/src/components/fields/ObjectField.js#L201

We're currently using a fork of this module: https://github.com/readmeio/api-explorer/blob/cf83d74fb7d18063f21906e232db24804acf8095/packages/api-explorer/package.json#L22 but I have to merge in the latest master anyway to get the `anyOf/oneOf` support for this: https://github.com/readmeio/api-explorer/issues/104

So maybe it will be fixed by default when we pull that in?

**Comment by nadalfederer** [comment]
Yeah, the latest version of `react-jsonschema-form` fixed that bug

**Comment by domharrington** [comment]
I just bumped this in here: https://github.com/readmeio/api-explorer/tree/fix/do-not-show-json-on-empty-object-declaration

Can you merge this branch into yours and repush to update this PR?

**Comment by nadalfederer** [comment]
@domharrington I've updated this branch

**Pull request merged**
